apiVersion: v1
kind: Service
metadata:
  name: webexample-lb
  labels:
    app: webexample
spec:
  selector:
    app: webexample
  ports:
    - name: http
      port: 7001
      targetPort: 80
  type: LoadBalancer