---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: {{.Values.ClientName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "{{.Values.ClientName}} app1 external"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: {{.Values.ClientName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "{{.Values.ClientName}} app2 internal"
---