apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: {{.Values.ClientName}}
spec:
  ports:
  - port: 8080
    targetPort: 80
    name: tcp
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: {{.Values.ClientName}}
spec:
  ports:
  - port: 8080
    targetPort: 80
    name: tcp8080
  - port: 8081
    targetPort: 80
    name: tcp8081
  selector:
    app: app2